### ISSUE TITLE
Retour sur maj algo

### ISSUE THREAD

**Issue by marcu** [be-lb/solar-loader#1]
Hello @pierremarc peux tu me donner ton retour sur les modifs faites lors de mon dernier commit.

# https://github.com/be-lb/solar-loader/blob/f79e480b1a17ca783fe8a3f2ae2270327c8e52d0/solar_loader/compute.py#L92 

- it peut aussi avoir le type Multipolygon. Dans ce cas là je le traite comme Polygon.
- it peut aussi avoir le type GeometryCollection. Dans ce cas là je n'ai pas encore traité, faire comme pour Polygon ?

# https://github.com/be-lb/solar-loader/blob/f79e480b1a17ca783fe8a3f2ae2270327c8e52d0/solar_loader/compute.py#L102

Cette ligne lance de temps en temps des exceptions, dans ce cas je fais comme quand `len(intersection) == 0` càd `return gis_triangle.area`

# https://github.com/be-lb/solar-loader/blob/f79e480b1a17ca783fe8a3f2ae2270327c8e52d0/solar_loader/final.py#L170

+ L171 le `insert_result` est après le raise -> jamais mis dans la db.

J'ai aussi retiré le `raise` car si on est là est qu'on a mis le résultat dans la db en `erreur` on peut passer à la suivante

**Comment by pierremarc** [comment]
Pour le cas des GeometryCollection, il me semble que c'est lorsqu'il insere d'autres type de geometries (points, lignes), donc on peut laisser tel quel.

Pour les exceptions de cascaded_union, tres bien, il me semblait l'avoir deja fait, ca  a du passer a la trape.

Et pour le raise, parfait, un residu de debuggage :/
